# Generated by Django 3.2.22 on 2023-10-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_clickcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ko', '한국어')], default=0, max_length=2),
        ),
    ]
