# Generated by Django 3.2.22 on 2023-10-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_userprofile_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickcount',
            name='house_click',
            field=models.IntegerField(default=0),
        ),
    ]
