# Generated by Django 3.2.22 on 2023-10-26 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_clickcount_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickcount',
            name='house',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mypage.house'),
        ),
    ]
