# Generated by Django 3.2.22 on 2023-10-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0008_clickcount_house_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickcount',
            name='apollo_click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clickcount',
            name='artemis_click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clickcount',
            name='athena_click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clickcount',
            name='poseidon_click',
            field=models.IntegerField(default=0),
        ),
    ]
