# Generated by Django 3.2.22 on 2023-10-27 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0008_alter_clickcount_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickcount',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.house'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ko', '한국어')], default='en', max_length=2),
        ),
    ]
