# Generated by Django 3.2.22 on 2023-10-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0009_auto_20231028_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apollo_click', models.IntegerField(default=0)),
                ('athena_click', models.IntegerField(default=0)),
                ('poseidon_click', models.IntegerField(default=0)),
                ('artemis_click', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='clickcount',
            name='apollo_click',
        ),
        migrations.RemoveField(
            model_name='clickcount',
            name='artemis_click',
        ),
        migrations.RemoveField(
            model_name='clickcount',
            name='athena_click',
        ),
        migrations.RemoveField(
            model_name='clickcount',
            name='house_click',
        ),
        migrations.RemoveField(
            model_name='clickcount',
            name='poseidon_click',
        ),
    ]
