# Generated by Django 3.2.22 on 2023-12-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0011_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='socre_count',
            new_name='score_count',
        ),
    ]
