# Generated by Django 3.2.22 on 2023-10-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20231018_2333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
